# Print and Filament presets are not necessary for this profile

inherits = 

name = Creality CXDLPv4 Test Printer
type = printer

# Size and shape properties
bed_shape = 0x0,164.64x0,164.64x92.16,0x92.16
max_print_height = 120
nozzle_diameter = 0.4

# Resolution
display_width = 1440
display_height = 1080
display_pixel_pitch_um = 127.0

# Default SLA output format - USE CXDLPV4
sla_archive_format = cxdlpv4

# Exposure parameters
initial_layer_height = 0.050
initial_exposure_time = 1.0
exposure_time = 0.8

# Lift parameters
initial_lift_height = 5.0
initial_lift_speed = 50.0
lift_height = 3.0
lift_speed = 50.0

# Retract parameters  
retract_speed = 50.0

# Support parameters
support_head_penetration = 0.4
support_object_elevation = 5.0

# Light PWM
default_sla_material_profile = Default SLA Material
